In [20]:
import pandas as pd 
df = pd.read_csv(r"reference\SchemeData0111251523SS.csv")
df

,AMC,Code,Scheme Name,Scheme Type,Scheme Category,Scheme NAV Name,Scheme Minimum Amount,Launch Date,Closure Date,ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment
0,Aditya Birla Sun Life AMC Limited,100033,Aditya Birla Sun Life Large & Mid Cap Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Large & Mid Cap Fund - R...,5000,24-Feb-1995,24-Feb-1995,INF209K01165
1,Aditya Birla Sun Life AMC Limited,100034,Aditya Birla Sun Life Large & Mid Cap Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Large & Mid Cap Fund -Re...,5000,24-Feb-1995,24-Feb-1995,INF209K01157INF209K01CE5
2,Aditya Birla Sun Life AMC Limited,119433,Aditya Birla Sun Life Large & Mid Cap Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Large & Mid Cap Fund -Di...,5000,24-Feb-1995,24-Feb-1995,INF209K01VG0INF209K01VI6
3,Aditya Birla Sun Life AMC Limited,119436,Aditya Birla Sun Life Large & Mid Cap Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Large & Mid Cap Fund - G...,5000,24-Feb-1995,24-Feb-1995,INF209K01VH8
4,Aditya Birla Sun Life AMC Limited,100037,Aditya Birla Sun Life Income Fund,Open Ended,Debt Scheme - Medium to Long Duration Fund,Aditya Birla Sun Life Income Fund - Regular - ...,5000,01-Jan-1994,01-Jan-1994,INF209K01587INF209K01CY3
...,...,...,...,...,...,...,...,...,...,...
16104,Old Bridge Asset Management Private Limited,153981,Old Bridge Arbitrage Fund,Open Ended,Hybrid Scheme - Arbitrage Fund,Old Bridge Arbitrage Fund - Direct - IDCW Payout,5000,06-Nov-2025,10-Nov-2025,INF0S5R01075
16105,Old Bridge Asset Management Private Limited,153976,Old Bridge Arbitrage Fund,Open Ended,Hybrid Scheme - Arbitrage Fund,Old Bridge Arbitrage Fund - Direct - IDCW Rein...,5000,06-Nov-2025,10-Nov-2025,INF0S5R01083
16106,Old Bridge Asset Management Private Limited,153977,Old Bridge Arbitrage Fund,Open Ended,Hybrid Scheme - Arbitrage Fund,Old Bridge Arbitrage Fund Regular Growth,5000,06-Nov-2025,10-Nov-2025,INF0S5R01091
16107,Old Bridge Asset Management Private Limited,153978,Old Bridge Arbitrage Fund,Open Ended,Hybrid Scheme - Arbitrage Fund,Old Bride Arbitrage Fund Regular IDCW Reinvest...,5000,06-Nov-2025,10-Nov-2025,INF0S5R01117
16108,Old Bridge Asset Management Private Limited,153979,Old Bridge Arbitrage Fund,Open Ended,Hybrid Scheme - Arbitrage Fund,Old Bridge Arbitrage Fund Direct Growth,5000,06-Nov-2025,10-Nov-2025,INF0S5R01125

In [21]:
prt = pd.read_csv("Portfolio_extracted_091125-0251.csv")
prt

,Name of Instrument,ISIN,Coupon,Industry,Quantity,Market Value,% to Net Assets,Yield,Type,Scheme Name,AMC,Scheme Name_df,isin_group,amfi_code
0,Embassy Office Parks REIT EOPR01,INE041025011,0.0,Realty,7.755070e+05,3272.096685,5.118641,0.00,Equity & Equity Related,360 ONE Dynamic Bond Fund - An Open Ended Dyn...,360 One Asset Management,360 one dynamic bond fund,"INF579M0118,INF579M0119,INF579M0121,INF579M012...","122612,122711,122712,122715,122717,122719,1227..."
1,Capital Infra Trust MEBP01,INE0Z8Z23013,0.0,Construction,2.525250e+06,1930.806150,3.020419,0.00,Equity & Equity Related,360 ONE Dynamic Bond Fund - An Open Ended Dyn...,360 One Asset Management,360 one dynamic bond fund,"INF579M0118,INF579M0119,INF579M0121,INF579M012...","122612,122711,122712,122715,122717,122719,1227..."
2,Brookfield India Real Estate Trust,INE0FDU25010,0.0,Realty,1.853180e+05,635.751931,0.994526,0.00,Equity & Equity Related,360 ONE Dynamic Bond Fund - An Open Ended Dyn...,360 One Asset Management,360 one dynamic bond fund,"INF579M0118,INF579M0119,INF579M0121,INF579M012...","122612,122711,122712,122715,122717,122719,1227..."
3,Mindspace Business Parks REIT,INE0CCU25019,0.0,Realty,1.203280e+05,547.239711,0.856064,0.00,Equity & Equity Related,360 ONE Dynamic Bond Fund - An Open Ended Dyn...,360 One Asset Management,360 one dynamic bond fund,"INF579M0118,INF579M0119,INF579M0121,INF579M012...","122612,122711,122712,122715,122717,122719,1227..."
4,6.4% Jamnagar Utilities & Power Private Limite...,INE936D07174,0.0,CRISIL AAA,3.000000e+06,2989.869000,4.677144,0.00,Equity & Equity Related,360 ONE Dynamic Bond Fund - An Open Ended Dyn...,360 One Asset Management,360 one dynamic bond fund,"INF579M0118,INF579M0119,INF579M0121,INF579M012...","122612,122711,122712,122715,122717,122719,1227..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53473,** 08.60 % SANSAR JAN 2025 TRUST - 25/10/2028 ^^,INE1WMT15017,0.0,CRISIL-AAA(SO),5.000000e+08,5010.500000,1.280000,8.73,Equity & Equity Related,TATA CORPORATE BOND FUND (The scheme has 1 seg...,Tata Mutual Fund,tata corporate bond fund,"INF277KA129,INF277KA133,INF277KA131,INF277KA13...","149351,149352,149353,149354,149355,149356,1493..."
53474,** 08.20 % INDIA UNIVERSAL TRUST AL1 - 20/09/2...,INE16J715035,0.0,IND-AAA(SO),4.700000e+01,4422.470000,1.130000,7.97,Equity & Equity Related,TATA CORPORATE BOND FUND (The scheme has 1 seg...,Tata Mutual Fund,tata corporate bond fund,"INF277KA129,INF277KA133,INF277KA131,INF277KA13...","149351,149352,149353,149354,149355,149356,1493..."
53475,** 08.85 % SANSAR JUNE 2024 TRUST - 25/08/2027...,INE0YWN15017,0.0,CRISIL-AAA(SO),7.500000e+08,3843.000000,0.980000,8.51,Equity & Equity Related,TATA CORPORATE BOND FUND (The scheme has 1 seg...,Tata Mutual Fund,tata corporate bond fund,"INF277KA129,INF277KA133,INF277KA131,INF277KA13...","149351,149352,149353,149354,149355,149356,1493..."
53476,** 08.17 % INDIA UNIVERSAL TRUST AL2 - 21/11/2...,INE1CBK15037,0.0,CRISIL-AAA(SO),2.400000e+01,2330.220000,0.600000,7.97,Equity & Equity Related,TATA CORPORATE BOND FUND (The scheme has 1 seg...,Tata Mutual Fund,tata corporate bond fund,"INF277KA129,INF277KA133,INF277KA131,INF277KA13...","149351,149352,149353,149354,149355,149356,1493..."
53477,SBIMF AIF - CAT I (CDMDF)27/10/2038,INF0RQ622028,0.0,NaN,9.344357e+03,1063.900000,0.270000,0.00,Equity & Equity Related,TATA CORPORATE BOND FUND (The scheme has 1 seg...,Tata Mutual Fund,tata corporate bond fund,"INF277KA129,INF277KA133,INF277KA131,INF277KA13...","149351,149352,149353,149354,149355,149356,1493..."

In [ ]:
prt.astype(str).assign(**{"temp" :prt["Scheme Name"].apply(lambda x : x.split("-")[0].strip())})

In [ ]:
import re
isin_pattern = r"[A-Z]{3}[A-Z0-9]{8}"
t = (
    prt.merge(
        df.astype(str).groupby("Scheme Name").agg({
                "ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment": ", ".join,
                "Code": ",".join
            }).reset_index()
            .assign(
            **{
                "ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment": 
                    lambda x: x["ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment"]
                                .apply(lambda s: ",".join(re.findall(isin_pattern, s)))
            }
        ),
        how = "left",
        left_on = prt["Scheme Name"].astype(str).apply(lambda x: x.split("-")[0].strip()),
        right_on = "Scheme Name",
        suffixes=("","_df")
    ).drop(columns=["Scheme Name_df"])
)
t

In [14]:
import re
pattern  = re.compile("|".join(["- an.*","-an.*", r"\(an.*", r"\( an.*", r"\(.*\)", "as on.*", r"[^a-z0-9\- ]"] ))

In [22]:
d1 = set(prt["Scheme Name"].str.lower().unique())
d2 = set(df["Scheme Name"].str.lower().unique())

In [16]:
["" if not i else pattern.sub("", str(i)) for i in d1]

['icici prudential smallcap fund',
 'quant gilt fund',
 'canara robeco corporate bond fund',
 'sbi nifty 200 quality 30 etf',
 'tata nifty500 multicap india manufacturing 50-30-20 index fund',
 'aditya birla sun life low duration fund',
 'icici prudential innovation fund',
 'shriram flexi cap fund',
 'aditya birla sun life balanced advantage fund',
 'icici prudential rural opportunities fund',
 'tata nifty india digital etf fund of fund',
 'sbi long term advantage fund - series v',
 'aditya birla sun life manufacturing equity fund',
 '360 one elss tax saver nifty 50 index fund ',
 'sundaram long term micro cap tax advantage fund series vi',
 'dsp mid cap fund',
 'nippon india etf bse sensex next 50 ',
 'tata bse quality index fund',
 'icici prudential nifty india consumption etf',
 '360 one dynamic bond fund  ',
 'nippon india floater fund ',
 'sbi corporate bond fund',
 'sbi elss tax saver fund',
 'quant value fund',
 'franklin india corporate debt fund',
 'mirae asset nifty bank etf',
 'jm midcap fund ',
 'icici prudential nifty alpha low- volatility 30 etf',
 'pgim india large and midcap fund',
 'icici prudential psu equity fund',
 'sundaram long term tax advantage fund series iii',
 'aditya birla sun life retirement fund - the 30s plan',
 'aditya birla sun life nifty 200 quality 30 etf',
 'mirae asset balanced advantage fund',
 'icici prudential equity - arbitrage fund',
 'canara robeco income fund',
 'bharat bond etf  april 2033 ',
 'tata nifty financial services index fund',
 'navi nifty 500 multicap 502525 index',
 'bank of india consumption fund  ',
 'sbi resurgent india opportunities scheme',
 'sbi midcap fund',
 'icici prudential nifty auto index fund',
 'nippon india dynamic bond fund ',
 'dsp regular savings fund',
 'groww multi asset allocation fund',
 'navi nifty 50 index fund',
 'bank of india large cap fund  ',
 'icici prudential technology fund',
 'sbi multi asset allocation fund',
 'tata treasury advantage fund ',
 'sbi savings fund',
 'icici prudential banking  psu debt fund',
 'quant business cycle fund',
 'icici prudential nifty 500 index fund',
 'sbi long term advantage fund - series iii',
 'hsbc large  mid cap fund',
 'groww banking  financial services fund',
 'edel nifty alpha low volatility 30 index fund ',
 'groww nifty 500 momentum 50 etf',
 'tata business cycle fund',
 'mirae asset great consumer fund',
 'mirae asset large cap fund',
 'edelweiss nifty500 multicap momentum quality 50 index fund ',
 'quant healthcare fund',
 'mirae asset money market fund',
 'icici prudential savings fund',
 'bank of india large  mid cap fund ',
 'nippon india value fund ',
 'edelweiss small cap fund ',
 'quant multi cap fund',
 'groww short duration fund',
 'bank of india overnight  fund ',
 'tata corporate bond fund ',
 'franklin india conservative hybrid fund ',
 'nippon india retirement fund - income generation scheme scheme having a lock-in of 5 years or till retirementage ',
 'icici prudential fmcg fund',
 'aditya birla sun life banking and financial services fund',
 'sundaram aggressive hybrid fund',
 'hsbc multi asset allocation fund',
 'icici prudential asset allocator fund ',
 'sbi esg exclusionary strategy fund',
 'tata dividend yield fund',
 'aditya birla sun life money manager fund',
 'aditya birla sun life esg integration strategy fund',
 'icici prudential housing opportunities fund',
 'hsbc aggressive hybrid fund',
 'sbi nifty50 equal weight index fund',
 'sundaram ultra short duration fund',
 'mirae asset nifty 200 alpha 30 etf fund of fund',
 'mirae asset nifty ev and new age automotive etf',
 'nippon india banking and psu fund ',
 'aditya birla sun life nifty 50 etf',
 'groww overnight fund',
 'sundaram small cap fund',
 'tata nifty midsmall healthcare index fund',
 'aditya birla sun life short term fund',
 'tata elss fund',
 'aditya birla sun life special opportunities fund',
 'icici prudential ultra short term fund',
 'tata retirement savings fund-conservative plan',
 'nippon india nifty alpha low volatility 30 index fund 30 index',
 'aditya birla sun life equity savings fund',
 'sundaram multi cap fund',
 'bharat bond fof  april 2030 ',
 'aditya birla sun life dynamic asset allocation omni fof',
 'dsp arbitrage fund',
 'tata banking  financial services fund',
 'icici prudential bse 500 etf',
 'groww silver etf fof',
 'dsp floater fund',
 'nippon india nifty pharma etf ',
 'nippon india flexi cap fund mid cap small cap stocks',
 'tata small cap fund',
 'groww nifty 200 etf',
 '360 one focused fund  ',
 'aditya birla sun life crisil-ibx aaa nbfc-hfc index - dec 2025 fund',
 'franklin india dynamic accrual fund - segregated portfolio 3 - 950 yes bank ltd co 23 dec 2021',
 'bank of india mid  small cap equity  debt fund ',
 'groww nifty 1d rate liquid etf',
 'icici prudential long term wealth enhancement fund',
 'aditya birla sun life crisil ibx 6040 sdl  aaa psu - apr 2027 index fund',
 'nippon india multi - asset omni fof ',
 'aditya birla sun life retirement fund - the 50s plan',
 'icici prudential dividend yield equity fund',
 'nippon india nifty aaa cpse bond plussdl - apr 2027 maturity 6040 index fundnifty aaa cpse bond plus sdl apr 2027 6040 index a relatively highinterest rate risk and relatively low credit risk',
 'quant dynamic asset allocation fund',
 'icici prudential multicap fund',
 'canara robeco focused fund',
 'nippon india focused fund ',
 'aditya birla sun life bse sensex etf',
 'quant commodities fund',
 'dsp india tiger fund ',
 'dsp nifty healthcare etf',
 '',
 'icici prudential regular gold savings fund ',
 'dsp savings fund',
 'aditya birla sun life multi asset allocation fund',
 'mirae asset equity savings fund',
 'franklin india short-term income plan  ',
 'aditya birla sun life small cap fund',
 'bank of india mid cap tax fund series 1 ',
 'canara robeco multi cap fund',
 'icici prudential energy opportunities fund',
 'mirae asset nifty500 multicap 502525 etf',
 'franklin india low duration fund',
 'icici prudential nifty 100 etf',
 'pgim india healthcare fund',
 'tata income plus arbitrage active fof',
 'aditya birla sun life retirement fund - the 50s plus - debt plan',
 'icici prudential equity  debt fund',
 'aditya birla sun life elss tax saver fund',
 'tata silver etf fund of fund',
 'quant focused fund',
 'sundaram banking  psu fund',
 'icici prudential money market fund',
 'edelweiss multi asset omni fund of fund ',
 'icici prudential nifty 50 etf',
 'tata retirement savings fund-progressive plan',
 'aditya birla sun life crisil-ibx financial services 3 to 6 months debt index fund',
 'canara robeco consumer trends fund',
 'aditya birla sun life bse india infrastructure index fund',
 'bank of india mid cap tax fund series 2 ',
 'franklin india elss tax saver fund  ',
 'sbi energy opportunities fund',
 'tata large  mid cap fund',
 'icici prudential nifty 50 index fund',
 'icici prudential nifty psu bank etf',
 'nippon india banking  financial services fund ',
 'pgim india arbitrage fund',
 'sundaram medium duration fund',
 'icici prudential nifty200 value 30 etf',
 'navi nifty india manufacturing indx fund',
 'edelweiss silver etf fund ',
 'nippon india income plus arbitrage active fund of fund ',
 'pgim india dynamic bond fund',
 'quant multi asset allocation fund',
 'dsp equity savings fund',
 'icici prudential bse midcap select etf',
 'icici prudential retirement fund - hybrid aggressive plan',
 'hsbc nifty 50 index fund',
 'nan',
 '360 one balanced hybrid fund -  an open ended balanced scheme investing in equity and debt instruments',
 'franklin india mid cap fund  ',
 'icici prudential nifty infrastructure etf',
 '360 one quant fund ',
 'hsbc consumption fund',
 'mirae asset bse sensex etf ',
 'mirae asset dynamic bond fund',
 'tata gold etf fund of fund',
 'aditya birla sun life conglomerate fund',
 'aditya birla sun life nifty 50 equal weight index fund',
 'edelweiss balanced advantage fund ',
 'pgim india aggressive hybrid equity fund',
 'dsp nifty top 10 equal weight index fund',
 'edelweiss nifty smallcap 250 index fund ',
 'nippon india short duration fund ',
 'sbi nifty midcap 150 index fund',
 'franklin india government securities fund',
 'bank of india ultra short duration fund ',
 'edelweiss nifty bank etf ',
 'dsp dynamic asset allocation fund',
 'aditya birla sun life dividend yield fund',
 'sbi bse 100 etf',
 'nippon india diversified equity flexicap passive fof domestic exchange traded funds ',
 'groww nifty next 50 index fund',
 'sbi floating rate debt fund',
 'icici prudential transportation and logistics fund',
 'sbi income plus arbitrage active fof',
 'tata nifty private bank exchange traded fund',
 'quant psu fund',
 'icici prudential liquid fund',
 'sbi short term debt fund',
 'sbi silver etf',
 'dsp strategic bond fund',
 'icici prudential balanced advantage fund',
 'groww nifty smallcap 250 index fund',
 'dsp nifty 50 equal weight etf',
 'tata ethical fund',
 'canara robeco large and mid cap fund',
 'mirae asset banking and psu fund ',
 'dsp nifty top 10 equal weight etf',
 'canara robeco flexicap fund',
 'canara robeco manufacturing fund',
 'franklin india dividend yield fund  ',
 'helios mid cap fund ',
 'bank of india short term income fund ',
 'tata india consumer fund',
 'navi nifty bank index fund',
 '360 one flexicap fund ',
 'dsp bond fund',
 'icici prudential active momentum fund',
 '',
 'nippon india nifty bank index fund',
 'aditya birla sun life bse 500 momentum 50 index fund',
 'pgim india multi cap fund',
 'hsbc small cap fund',
 'dsp small cap fund',
 'quantum nifty 50 etf ',
 'dsp nifty 50 equal weight index fund',
 'edelweiss focused fund ',
 'navi flexi cap fund',
 'aditya birla sun life nifty pse etf',
 'nippon india nifty 500 momentum 50 index fund',
 'sbi long term advantage fund - series iv',
 'edelweiss nifty next 50 index fund ',
 'tata short term bond fund ',
 'sundaram liquid fund',
 'dsp focused fund',
 'icici prudential india opportunities fund',
 'mirae asset ultra short duration fund',
 'hsbc midcap fund',
 'dsp nifty bank etf',
 'mirae asset nifty 50 etf',
 'sundaram elss tax saver fund',
 'aditya birla sun life bal bhavishya yojna',
 '',
 'pgim india liquid fund',
 'nippon india nifty 500 equal weight index fund',
 'canara robeco short duration fund',
 'nippon india power  infra fund ',
 'mirae asset bse select ipo etf',
 'sbi smallcap fund',
 '360 one multi asset allocation fund ',
 'sundaram infrastructure advantage fund',
 'edelweiss nifty psu bond plus sdl apr 2026 50 50 index fund ',
 'icici prudential large cap fund',
 'dsp banking and psu debt fund',
 'icici prudential mnc fund',
 'aditya birla sun life income fund',
 'groww nifty ev  new age automotive etf',
 'franklin india money market fund  ',
 'franklin india multi asset allocation fund',
 'hsbc tax saver equity fund',
 'icici prudential nifty pharma index fund',
 'icici prudential nifty200 quality 30 index fund',
 'sbi long duration fund',
 'sbi nifty india consumption index fund',
 'aditya birla sun life income plus arbitrage active fof',
 'mirae asset liquid fund ',
 'nippon india etf nifty next 50 junior bees ',
 'tata nifty midcap 150 index fund',
 'tata nifty capital markets index fund',
 'bank of india small cap fund ',
 'sbi psu fund',
 'sundaram equity savings fund',
 'edelweiss money market fund ',
 'hsbc nifty next 50 index fund',
 'groww multicap fund',
 'sbi nifty index fund',
 'quantum multi asset allocation fund ',
 'dsp income plus arbitrage omni fof',
 'sbi retirement benefit fund - aggressive hybrid plan',
 'sbi dividend yield fund',
 'corporate bonds a relatively high interest rate risk and relatively high credit risk',
 'tata multicap fund',
 'icici prudential nifty alpha low - volatility 30 etf fof',
 'dsp healthcare fund',
 'dsp bse sensex next 30 etf',
 'sbi banking  psu fund',
 'nippon india etf nifty it ',
 '',
 'icici prudential credit risk fund',
 'mirae asset nifty 100 esg sector leaders etf',
 'aditya birla sun life nifty smallcap 50 index fund',
 'quant esg integration strategy fund',
 'nippon india liquid fund ',
 'franklin build india fund',
 'icici prudential nifty50 value 20 index fund',
 'bank of india conservative hybrid fund ',
 'edelweiss nifty psu bond plus sdl apr 2027 50 50 index ',
 'dsp corporate bond fund',
 'franklin india ultra short duration fund',
 'sundaram services fund',
 'icici prudential nifty50 equal weight index fund',
 'bank of india mid cap fund  ',
 'dsp nifty it etf',
 'bharat bond etf  april 2031 ',
 'hsbc financial services fund',
 'sbi infrastructure fund',
 'sbi conservative hybrid fund',
 'icici prudential corporate bond fund',
 'mirae asset large  midcap fund ',
 'sbi healthcare opportunities fund',
 'sbi nifty bank index fund',
 'franklin india focused equity fund',
 'groww nifty india railways psu index',
 'icici prudential floating interest fund',
 'aditya birla sun life liquid fund',
 'mirae asset nifty india manufacturing etf',
 'quant teck fund',
 'bharat bond etf  april 2032 ',
 'shriram liquid fund',
 'mirae asset nifty it etf',
 'nippon india bse sensex next 30 etf ',
 'nippon india quarterly interval fund-series 2 ',
 'bank of india credit risk fund ',
 'nippon india equity savings fund ',
 'sbi magnum income fund',
 'aditya birla sun life nifty 200 momentum 30 etf',
 'sbi focused fund',
 'dsp nifty next 50 index fund',
 '',
 'nippon india balanced advantage fund ',
 'edelweiss low duration fund ',
 'dsp business cycle fund',
 'franklin india technology fund',
 'groww dynamic bond fund',
 'icici prudential banking  financial services fund',
 'quant arbitrage fund',
 'nippon india crisil - ibx aaa financial services - dec 2026 index fund ',
 'groww nifty india railways psu etf',
 'nippon india quant fund ',
 'nippon india nifty next 50 junior bees fof nippon india etf junior bees',
 'icici prudential medium term bond fund',
 'sbi gold etf',
 'sbi balanced advantage fund',
 'hsbc india export opportunities fund',
 'mirae asset nifty financial services etf',
 'tata balanced advantage fund',
 'nippon india bse sensex next 30 index fund ',
 'tata equity savings fund',
 'aditya birla sun life credit risk fund - no of segregated portfolio - 1',
 'sbi comma fund',
 'sbi innovative opportunities fund',
 'franklin india income plus arbitrage active fund of funds ',
 'icici prudential elss tax saver fund',
 '',
 'nippon india small cap fund ',
 'sundaram value fund',
 'groww nifty next 50 etf',
 'edelweiss  banking and psu debt fund ',
 'sbi nifty next 50 etf',
 'icici prudential nifty it etf',
 'sbi nifty50 equal weight etf',
 'navi liquid fund',
 'franklin india banking  psu debt fund',
 'sbi equity minimum variance fund',
 'canara robeco banking and psu debt fund',
 'bank of india balanced advantage fund ',
 'mirae asset bse 200 equal weight etf',
 'icici prudential bharat 22 fof',
 'icici prudential nifty top 15 equal weight etf',
 'aditya birla sun life nifty india defence index fund',
 'franklin india balanced advantage fund',
 'aditya birla sun life crisil-ibx financial services 9-12 months debt index fund',
 'sbi fixed maturity plan - series 78',
 'icici prudential bond fund',
 'edelweiss crisil-ibx aaa bond nbfc-hfc - jun 2027 index fund ',
 '',
 'icici prudential commodities fund',
 'icici prudential nifty bank etf',
 'franklin india opportunities fund',
 'sbi automotive opportunities fund',
 'icici prudential bse sensex etf',
 'nippon india retirement fund - wealth creation scheme scheme having a lock-in of 5 years or till retirementage ',
 'sundaram low duration fund',
 'quant bfsi fund',
 'mirae asset diversified equity allocator passive fof ',
 'icici prudential business cycle fund',
 'shriram multi asset allocation fund',
 'shriram balanced advantage fund',
 'nippon india nifty india manufacturing etf ',
 'edelweiss elss tax saver fund ',
 'sbi dynamic bond fund',
 'tata money market fund',
 'sbi magnum childrens benefit fund- investment plan',
 'moderate credit risk',
 'canara robeco savings fund',
 'dsp quant fund',
 'aditya birla sun life nifty it etf',
 'bharat bond fof  april 2032 ',
 'tata liquid fund',
 'icici prudential passive strategy fund ',
 'edelweiss gold and silver etf fof ',
 'mirae asset nifty india new age consumption etf',
 'edelweiss mid cap fund ',
 'nippon india etf hang seng bees ',
 'sbi bse sensex etf',
 'aditya birla sun life digital india fund',
 'aditya birla sun life infrastructure fund',
 'edelweiss  liquid fund ',
 'sbi magnum ultra short duration fund',
 'sbi large cap fund',
 'franklin india medium to long duration fund',
 'aditya birla sun life crisil ibx 6040 sdl  aaa psu apr 2026 index fund',
 'franklin india large  mid cap fund ',
 'hsbc multi asset active fof',
 'mirae asset nifty 200 alpha 30 etf',
 'sbi retirement benefit fund - aggressive plan',
 'aditya birla sun life equity hybrid 95 fund',
 'icici prudential nifty 100 low volatility 30 etf fof',
 'dsp nifty500 flexicap quality 30 index fund',
 'icici prudential nifty ev  new age automotive etf',
 'nippon india innovation fund',
 'nippon india growth mid cap fund ',
 'sbi quant fund',
 'sundaram conservative hybrid fund',
 'nippon india pharma fund ',
 'canara robeco ultra short term fund',
 'nippon india ultra short duration fund ',
 'pgim india small cap fund',
 'icici prudential nifty psu bond plus sdl sep 2027 4060 index fund',
 'sundaram dividend yield fund',
 'tata housing opportunities fund',
 'nippon india nifty midcap 150 index fund ',
 'mirae asset elss tax saver fund ',
 'aditya birla sun life bse 500 quality 50 index fund',
 'sundaram corporate bond fund',
 'canara robeco conservative hybrid fund',
 '360 one liquid fund ',
 'jm value fund ',
 'sundaram long term micro cap tax advantage fund series iii',
 'icici prudential nifty fmcg etf',
 'canara robeco equity hybrid fund',
 'mirae asset corporate bond fund',
 '',
 'hsbc elss tax saver fund',
 'jm large cap fund ',
 'franklin india aggressive hybrid fund ',
 'bank of india manufacturing and infrastructure fund ',
 'quantum nifty 50 etf fund of fund ',
 'groww nifty 500 low volatility 50 etf',
 'bank of india business cycle fund  ',
 'dsp nifty psu bank etf',
 'mirae asset sp 500 top 50 etf fund of fund',
 'dsp liquidity fund',
 'nippon india multi asset allocation fund and exchange traded commodity derivatives and gold etf  silver etf',
 'sundaram long term micro cap tax advantage fund series iv',
 'helios large  mid cap fund ',
 'mirae asset aggressive hybrid fund ',
 'nippon india crisil - ibx aaa financial services - jan 2028 index fund ',
 'aditya birla sun life multi  asset passive fof',
 'quantum elss tax saver fund ',
 'navi elss tax saver fund',
 'nippon india active momentum fund ',
 'aditya birla sun life pharma  healthcare fund',
 'sbi retirement benefit fund - conservative hybrid plan',
 'mirae asset flexi cap fund',
 'nippon india vision large  mid cap fund ',
 'icici prudential pharma healthcare and diagnostics  fund',
 'sundaram focused  fund',
 'helios balanced advantage fund ',
 'sbi magnum childrens benefit fund - savings plan',
 'sundaram multi asset allocation fund',
 'tata floating rate fund',
 'aditya birla sun life nifty midcap 150 index fund',
 'aditya birla sun life crisil-ibx aaa financial services index-sep 2027 fund',
 'hsbc business cycles fund',
 'quant aggressive hybrid fund',
 'sbi consumption opportunities fund',
 'icici prudential income plus arbitrage active fof',
 'canara robeco liquid fund',
 'icici prudential nifty next 50 index fund',
 'sundaram consumption fund',
 'nippon india nifty india manufacturing index fund ',
 'nippon india index fund - bse sensex plan ',
 'sbi nifty smallcap 250 index fund',
 'sundaram mid cap fund',
 'sbi nifty 10 yr benchmark g-sec etf',
 'edelweiss equity savings fund ',
 'dsp aggressive hybrid fund',
 'nippon india fixed maturity plan - xlv - series 5 a close ended scheme relatively high interest rate risk and relatively high credit risk ',
 'aditya birla sun life long duration fund',
 'pgim india midcap fund',

In [27]:
import re
def clean(scheme_name):
    scheme_name = str(scheme_name)
    patterns  =  ["- an.*","-an.*", r"\(an.*", r"\( an.*", r"\([^)]*\)", "as on.*", "scheme having.*"]
    scheme_name = scheme_name.lower()
    for pattern in patterns:
        scheme_name = re.sub(pattern, "", scheme_name)
    scheme_name = re.sub( r"[^a-z0-9\- ]", " ", scheme_name)
    scheme_name = re.sub(r"\s+"," ",scheme_name)

    return scheme_name

In [28]:
clean("60:50 hello (max)  game")

'60 50 hello game'

In [29]:
[clean(i) for i in d1]

['canara robeco equity hybrid fund',
 'bank of india mid small cap equity debt fund ',
 'canara robeco corporate bond fund',
 'nippon india etf nifty bank bees ',
 'icici prudential smallcap fund',
 'canara robeco balanced advantage fund',
 'tata nifty private bank exchange traded fund',
 'pgim india corporate bond fund',
 'hsbc nifty next 50 index fund',
 'aditya birla sun life large mid cap fund',
 'icici prudential equity minimum variance fund',
 '',
 'sbi infrastructure fund',
 'quant dynamic asset allocation fund',
 'jm value fund ',
 'sbi nifty bank index fund',
 'nippon india etf nifty 50 value 20 ',
 'quant flexi cap fund',
 'mirae asset arbitrage fund',
 'dsp healthcare fund',
 'quantum liquid fund ',
 'sundaram infrastructure advantage fund',
 'mirae asset bse select ipo etf',
 'edel nifty alpha low volatility 30 index fund ',
 'pgim india arbitrage fund',
 'sundaram large cap fund',
 'nippon india nivesh lakshya long duration fund ',
 'tata nifty 50 exchange traded fund',
 'nippon india multi - asset omni fof ',
 'sbi nifty 200 quality 30 etf',
 'dsp mid cap fund',
 'franklin india multi cap fund',
 'aditya birla sun life crisil-ibx aaa nbfc-hfc index - dec 2025 fund',
 'icici prudential crisil-ibx financial services 3-6 months debt index fund',
 'icici prudential nifty50 value 20 etf',
 'canara robeco conservative hybrid fund',
 'quantum nifty 50 etf fund of fund ',
 'dsp business cycle fund',
 '360 one gold etf ',
 'aditya birla sun life flexi cap fund',
 'shriram balanced advantage fund',
 'icici prudential dividend yield equity fund',
 'navi nifty next 50 index fund',
 'hsbc multi cap fund',
 'bharat bond fof april 2030 ',
 'icici prudential manufacturing fund',
 'aditya birla sun life large cap fund',
 'nippon india crisil - ibx aaa financial services - dec 2026 index fund ',
 'icici prudential nifty midcap 150 index fund',
 'dsp multicap fund',
 'aditya birla sun life value fund',
 'dsp arbitrage fund',
 'pgim india healthcare fund',
 'tata resources energy fund',
 'tata nifty india digital etf fund of fund',
 'pgim india multi cap fund',
 'mirae asset bse select ipo etf fund of fund',
 'icici prudential nifty ev new age automotive etf fof',
 'bank of india arbitrage fund ',
 'franklin india dynamic asset allocation active fund of funds ',
 'dsp nifty it index fund',
 'nippon india nifty auto etf ',
 'nippon india nifty india manufacturing index fund ',
 'sbi long duration fund',
 'bank of india conservative hybrid fund ',
 'sbi consumption opportunities fund',
 'franklin india income plus arbitrage active fund of funds ',
 'icici prudential technology fund',
 'icici prudential ultra short term fund',
 'sbi elss tax saver fund',
 'sbi retirement benefit fund - aggressive plan',
 'aditya birla sun life savings fund',
 'icici prudential nifty50 equal weight index fund',
 'aditya birla sun life nifty 50 equal weight index fund',
 'icici prudential nifty bank index fund',
 'dsp value fund',
 'groww elss tax saver fund',
 'icici prudential nifty oil gas etf',
 'sbi retirement benefit fund - aggressive hybrid plan',
 'canara robeco multi cap fund',
 'mirae asset midcap fund',
 'tata nifty financial services index fund',
 'groww nifty 500 low volatility 50 etf',
 'dsp strategic bond fund',
 'franklin india retirement fund ',
 'hsbc large mid cap fund',
 'nippon india nifty 500 equal weight index fund',
 'dsp dynamic asset allocation fund',
 'icici prudential nifty auto etf',
 'bank of india credit risk fund ',
 'tata nifty500 multicap india manufacturing 50-30-20 index fund',
 'tata nifty auto index fund',
 'sundaram focused fund',
 'navi elss tax saver fund',
 'tata nifty sdl plus aaa psu bond dec 2027 60 40 index fund',
 'nippon india bse sensex next 30 etf ',
 'franklin india low duration fund',
 'icici prudential banking financial services fund',
 'tata corporate bond fund ',
 'icici prudential passive strategy fund ',
 'nippon india nifty smallcap 250 index fund ',
 'tata liquid fund',
 'aditya birla sun life retirement fund - the 50s plus - debt plan',
 'sbi fixed maturity plan - series 76',
 'sbi income plus arbitrage active fof',
 'dsp large mid cap fund',
 'bank of india short term income fund ',
 'dsp floater fund',
 'icici prudential bond fund',
 'icici prudential credit risk fund',
 'nippon india nifty alpha low volatility 30 index fund 30 index ',
 'nippon india etf nifty psu bank bees ',
 'mirae asset bse 200 equal weight etf',
 'sbi focused fund',
 ' option',
 'quant aggressive hybrid fund',
 'icici prudential elss tax saver fund',
 'icici prudential rural opportunities fund',
 'icici prudential nifty private bank etf',
 'mirae asset hang seng tech etf',
 'mirae asset money market fund',
 'tata equity savings fund',
 'aditya birla sun life aggressive hybrid omni fof',
 'mirae asset short duration fund ',
 'edel bse capital markets insurance etf ',
 'franklin india government securities fund',
 'dsp focused fund',
 'icici prudential nifty 200 momentum 30 etf',
 'mirae asset banking and psu fund ',
 'tata nifty 50 index fund',
 'nippon india etf nifty it ',
 'canara robeco focused fund',
 'mirae asset nifty india manufacturing etf',
 'sbi dividend yield fund',
 'aditya birla sun life digital india fund',
 'mirae asset nifty 100 low volatility 30 etf',
 'quant mid cap fund',
 'sbi fixed maturity plan - series 78',
 'icici prudential business cycle fund',
 'edelweiss money market fund ',
 'sbi nifty midcap 150 index fund',
 'tata large mid cap fund',
 'edelweiss small cap fund ',
 'sundaram financial services opportunities fund',
 'aditya birla sun life equity hybrid 95 fund',
 'quant large cap fund',
 'dsp nifty 50 etf',
 'sbi magnum children s benefit fund - savings plan',
 'hsbc focused fund',
 'nippon india medium to long duration fund ',
 'mirae asset banking and financial services fund',
 'nippon india crisil - ibx aaa financial services - jan 2028 index fund ',
 'quant liquid fund',
 'aditya birla sun life nifty next 50 index fund',
 'franklin india elss tax saver fund ',
 'dsp short term fund',
 'mirae asset nifty 100 esg sector leaders etf',
 'nippon india multi cap fund multi cap fund ',
 'aditya birla sun life long duration fund',
 'aditya birla sun life retirement fund - the 40s plan',
 'dsp natural resources new energy fund',
 'aditya birla sun life banking and financial services fund',
 'dsp corporate bond fund',
 'edelweiss nifty largemidcap 250 etf ',
 'icici prudential nifty india consumption etf',
 'icici prudential nifty it index fund',
 'navi aggressive hybrid fund',
 'nippon india conservative hybrid fund ',
 'sbi nifty next 50 index fund',
 'groww nifty india railways psu index',
 'nippon india banking financial services fund ',
 'cpse etf ',
 'quant focused fund',
 'icici prudential nifty 100 low volatility 30 etf',
 'mirae asset nifty india new age consumption etf fund of fund',
 'groww gilt fund',
 'icici prudential asset allocator fund ',
 'aditya birla sun life nifty india defence index fund',
 'mirae asset multicap fund',
 'sbi nifty 50 etf',
 'sundaram elss tax saver fund',
 'hsbc aggressive hybrid fund',
 'icici prudential children s fund',
 'nippon india retirement fund - wealth creation scheme age ',
 '360 one focused fund ',
 'tata retirement savings fund-moderate plan',
 'edelweiss liquid fund ',
 'icici prudential all seasons bond fund',
 'nippon india nifty 500 quality 50 index fund ',
 'icici prudential bse sensex etf',
 'sbi psu fund',
 'dsp bse sensex next 30 etf',
 'aditya birla sun life floating rate fund',
 'mirae asset long duration fund',
 'mirae asset healthcare fund',
 'nippon india nifty india manufacturing etf ',
 'quantum value fund ',
 'mirae asset ultra short duration fund',
 'bank of india business cycle fund ',
 'navi nifty 50 index fund',
 'quantum nifty 50 etf ',
 '',
 'canara robeco consumer trends fund',
 'icici prudential nifty auto index fund',
 'icici prudential nifty200 value 30 index fund',
 'franklin india banking psu debt fund',
 'icici prudential nifty 50 etf',
 'sbi conservative hybrid fund',
 '',
 'nippon india nifty 500 low volatility 50 index fund ',
 'nippon india dynamic bond fund ',
 'quant esg integration strategy fund',
 'icici prudential nifty50 value 20 index fund',
 'icici prudential nifty top 15 equal weight index fund',
 'aditya birla sun life nifty it etf',
 'tata nifty capital markets index fund',
 'franklin u s opportunities equity active fund of funds ',
 'pgim india liquid fund',
 'mirae asset nifty 200 alpha 30 etf fund of fund',
 'tata business cycle fund',
 'nan',
 'sbi bse 100 etf',
 'sundaram multi asset allocation fund',
 'dsp multi asset allocation fund',
 'quant momentum fund',
 'helios financial services fund ',
 'aditya birla sun life mnc fund',
 'edelweiss nifty next 50 index fund ',
 'canara robeco ultra short term fund',
 'mirae asset great consumer fund',
 'edelweiss nifty psu bond plus sdl apr 2026 50 50 index fund ',
 'icici prudential fmcg fund',
 'bank of india large mid cap fund ',
 'icici prudential nasdaq 100 index fund',
 'pgim india equity savings fund',
 'aditya birla sun life nifty 200 quality 30 etf',
 'edelweiss consumption fund ',
 'franklin india arbitrage fund',
 'icici prudential corporate bond fund',
 'tata bse sensex index fund',
 'edelweiss business cycle fund ',
 'nippon india arbitrage fund ',
 'icici prudential bharat consumption fund',
 'icici prudential nifty smallcap 250 index fund',
 'hsbc financial services fund',
 'sbi nifty it index fund',
 'dsp nifty smallcap250 quality 50 index fund',
 'dsp bse sensex next 30 index fund',
 'mirae asset nifty 200 alpha 30 etf',
 'tata india consumer fund',
 'nippon india money market fund ',
 'shriram liquid fund',
 'nippon india liquid fund ',
 'sundaram mid cap fund',
 'hsbc aggressive hybrid active fof',
 'pgim india retirement fund',
 'aditya birla sun life small cap fund',
 'sbi bse sensex etf',
 'hsbc midcap fund',
 'aditya birla sun life nifty healthcare etf',
 'sundaram corporate bond fund',
 'tata value fund',
 'hsbc arbitrage fund',
 'tata nifty midcap 150 index fund',
 'groww value fund',
 'franklin india dividend yield fund ',
 'groww multi asset allocation fund',
 'groww nifty smallcap 250 index fund',
 'navi liquid fund',
 'quant elss tax saver fund',
 'sbi nifty consumption etf',
 'hsbc multi asset active fof',
 'sbi nifty smallcap 250 index fund',
 'aditya birla sun life transportation and logistics fund',
 'sbi flexicap fund',
 'sundaram arbitrage fund',
 'canara robeco savings fund',
 'edelweiss nifty psu bond plus sdl apr 2027 50 50 index ',
 'sbi banking psu fund',
 'sbi nifty 10 yr benchmark g-sec etf',
 'tata multicap fund',
 'tata ethical fund',
 'icici prudential nifty infrastructure etf',
 'bank of india multi asset allocation fund ',
 'pgim india small cap fund',
 'mirae asset nifty india manufacturing etf fund of fund',
 'bank of india flexi cap fund ',
 'hsbc nifty 50 index fund',
 'mirae asset nifty psu bank etf',
 'franklin india floating rate fund',
 'franklin india long duration fund',
 'franklin india technology fund',
 'bank of india large cap fund ',
 'aditya birla sun life dividend yield fund',
 'aditya birla sun life income fund',
 'sbi bse psu bank etf',
 'sbi bse sensex index fund',
 'aditya birla sun life business cycle fund',
 'icici prudential nifty metal etf',
 'franklin india ultra short duration fund',
 'canara robeco banking and psu debt fund',
 'nippon india etf nifty dividend opportunities 50 ',
 'icici prudential long term wealth enhancement fund',
 'navi large midcap fund',
 'canara robeco short duration fund',
 'aditya birla sun life conglomerate fund',
 'dsp nifty midcap 150 qlty 50 index fund',
 'nippon india equity savings fund ',
 'canara robeco liquid fund',
 'hsbc value fund',
 'canara robeco flexicap fund',
 'dsp india t i g e r fund ',
 'pgim india ultra short duration fund',
 'sbi equity hybrid fund',
 'sbi magnum children s benefit fund- investment plan',
 'helios balanced advantage fund ',
 'nippon india etf bse sensex next 50 ',
 'tata digital india fund',
 'icici prudential nifty 500 index fund',
 'sbi nifty private bank etf',
 'aditya birla sun life crisil-ibx aaa nbfc-hfc index - sep 2026 fund',
 'sundaram long term micro cap tax advantage fund series v',
 'bharat bond etf april 2030 ',
 'franklin india dynamic accrual fund - segregated portfolio 3 - 9 50 yes bank ltd co 23 dec 2021',
 'aditya birla sun life crisil-ibx aaa financial services index-sep 2027 fund',
 'tata money market fund',
 'nippon india pharma fund ',
 'nippon india mnc fund ',
 'nippon india taiwan equity fund ',
 'canara robeco dynamic bond fund',
 'dsp nifty midcap 150 quality 50 etf',
 'sbi long term advantage fund - series vi',
 'sbi magnum income fund',
 'edelweiss large cap fund ',
 'tata multi asset allocation fund',
 'mirae asset nifty india new age consumption etf',
 'quant overnight fund',
 'edelweiss nifty smallcap 250 index fund ',
 'templeton india value fund',
 'pgim india large cap fund',
 'tata childrens fund',
 'hsbc multi asset allocation fund',
 'tata bse select business groups index fund',
 'aditya birla sun life arbitrage fund',
 ' moderate credit risk ',
 'icici prudential money market fund',
 'dsp quant fund',
 'sbi retirement benefit fund - conservative hybrid plan',
 'aditya birla sun life crisil-ibx financial services 3 to 6 months debt index fund',
 'shriram multi sector rotation fund',
 'mirae asset bse sensex etf ',
 'nippon india nifty next 50 junior bees fof nippon india etf junior bees ',
 'dsp equity savings fund',
 'sbi long term advantage fund - series v',
 'nippon india etf nifty next 50 junior bees ',
 'icici prudential crisil-ibx aaa bond financial services index - dec 2026 fund',
 'icici prudential bse 500 etf',
 'aditya birla sun life nifty next 50 etf',
 'sbi savings fund',
 'aditya birla sun life dynamic asset allocation omni fof',
 'pgim india flexi cap fund',
 'icici prudential global advantage fund ',
 'franklin india focused equity fund',
 'icici prudential large mid cap fund',
 'sundaram flexi cap fund',
 'aditya birla sun life retirement fund - the 30s plan',
 'edelweiss nifty 50 index fund ',
 'aditya birla sun life international equity fund',
 'tata ultra short term fund',
 'sbi large and midcap fund',
 'bharat bond fof april 2032 ',
 'icici prudential transportation and logistics fund',
 'mirae asset nifty smallcap 250 momentum quality 100 etf',
 'nippon india etf nifty 100 ',
 'sbi gold etf',
 'mirae asset bse 200 equal weight etf fund of fund',
 'aditya birla sun life credit risk fund - no of segregated portfolio - 1',
 'edelweiss nifty bank etf ',
 'franklin build india fund',
 'sbi corporate bond fund',
 'sundaram medium duration fund',
 'edelweiss aggressive hybrid fund ',
 'icici prudential equity - arbitrage fund',
 'sundaram long term micro cap tax advantage fund series iii',
 'icici prudential nifty fmcg etf',
 'sundaram nifty 100 equal weight fund',
 'tata flexi cap fund',
 '360 one silver etf ',
 'helios flexi cap fund mid cap small cap stocks ',
 'quant bfsi fund',
 'edelweiss nifty500 multicap momentum quality 50 etf ',
 'sbi automotive opportunities fund',
 'quantum ethical fund ',
 'aditya birla sun life special opportunities fund',
 'franklin india corporate debt fund',
 'edelweiss multi cap fund ',
 'groww dynamic bond fund',
 'edelweiss technology fund ',
 'dsp nifty bank etf',
 'sbi fixed maturity plan - series 81',
 'aditya birla sun life quant fund',
 'edelweiss nifty large mid cap 250 index fund ',
 'groww multicap fund',
 'aditya birla sun life consumption fund',
 'aditya birla sun life bse 500 momentum 50 index fund',
 'pgim india dynamic bond fund',
 'edelweiss bse internet economy index fund ',
 'icici prudential nifty200 quality 30 index fund',
 'tata nifty500 multicap infrastructure 50-30-20 index fund',
 'dsp flexi cap fund',
 'icici prudential nifty 100 etf',
 'icici prudential regular savings fund',
 'aditya birla sun life bse 500 quality 50 index fund',
 'aditya birla sun life nifty 50 index fund',
 'franklin india liquid fund',
 'nippon india vision large mid cap fund ',
 'quantum elss tax saver fund ',
 'quantum diversified equity all cap active fof ',
 'sbi esg exclusionary strategy fund',
 'dsp credit risk fund',
 'franklin india large cap fund ',
 'icici prudential retirement fund - pure equity plan',
 'icici prudential esg exclusionary strategy fund',
 'mirae asset dynamic bond fund',
 'sbi mnc fund',
 'mirae asset multi asset allocation fund',
 '360 one multi asset allocation fund ',
 'nippon india credit risk fund ',
 'dsp banking financial services fund',
 'icici prudential large cap fund',
 'sbi resurgent india opportunities scheme',
 '',
 'nippon india etf nifty midcap 150 ',
 'groww nifty 500 momentum 50 etf fof',
 'canara robeco income fund',
 'nippon india index fund - nifty 50 plan ',
 'canara robeco manufacturing fund',
 'dsp nifty 50 index fund',
 'groww aggressive hybrid fund',
 'hsbc consumption fund',
 'mirae asset large midcap fund ',
 'dsp nifty top 10 equal weight index fund',
 '',
 'sbi liquid fund',
 'aditya birla sun life crisil ibx 60 40 sdl aaa psu apr 2026 index fund',
 'icici prudential flexicap fund',
 'navi nifty smallcap250 momentum qlty 100',
 'quant teck fund',
 '',
 'groww nifty india defence etf',
 'sbi short term debt fund',
 'mirae asset nifty total market index fund',
 'dsp nifty bank index fund',
 'jm midcap fund ',
 'canara robeco large cap fund',
 'mirae asset nifty next 50 etf',
 'nippon india medium duration fund ',
 'aditya birla sun life esg integration strategy fund',
 'quant gilt fund',
 'franklin india medium to long duration fund',
 'edelweiss recently listed ipo fund ',
 'icici prudential nifty largemidcap 250 index fund',
 'mirae asset nifty midsmallcap400 momentum quality 100 etf',
 'sbi credit risk fund',
 'tata housing opportunities fund',
 'edelweiss crl psu pl sdl 50 50 oct-25 fd ',
 'edelweiss balanced advantage fund ',
 'icici prudential equity debt fund',
 'dsp nifty psu bank etf',
 'sundaram aggressive hybrid fund',
 'aditya birla sun life medium term plan - no of segregated portfolio - 1',
 'icici prudential exports and services fund',
 'icici prudential nifty commodities etf',
 'icici prudential short term fund',
 'aditya birla sun life retirement fund - the 50s plan',
 'franklin india opportunities fund',
 'icici prudential income plus arbitrage active fof',
 'sbi nifty50 equal weight etf',
 'sundaram equity savings fund',
 'sundaram money market fund',
 'tata focused fund',
 'edelweiss banking and psu debt fund ',
 'shriram elss tax saver fund',
 'navi flexi cap fund',
 'dsp aggressive hybrid fund',
 'aditya birla sun life equity savings fund',
 'nippon india etf nifty 50 shariah bees ',
 'dsp large cap fund',
 'quantum small cap fund ',
 'icici prudential quant fund',
 'mirae asset balanced advantage fund',
 'sbi silver etf',
 'bharat bond etf april 2033 ',
 'icici prudential focused equity fund',
 'sbi large cap fund',
 'sundaram short duration fund',
 'franklin india small cap fund ',
 'hsbc balanced advantage fund',
 'dsp nifty next 50 index fund',
 'icici prudential debt management fund ',
 'tata banking financial services fund',
 'dsp small cap fund',
 'tata floating rate fund',
 'tata gold etf fund of fund',
 'sbi dynamic bond fund',
 'icici prudential long term bond fund',
 'bharat bond fof april 2033 ',
 'groww liquid fund',
 'edelweiss crisil ibx aaa financial services bond jan 2028 index fund ',
 'quant value fund',
 'sbi long term advantage fund - series iv',
 'bank of india consumption fund ',
 'quant quantamental fund',
 'dsp low duration fund',
 'tata small cap fund',
 'icici prudential banking psu debt fund',
 'icici prudential india equity ',
 'edelweiss low duration fund ',
 'tata nifty india tourism index fund',
 'canara robeco multi asset allocation fund',
 'aditya birla sun life balanced advantage fund',
 'mirae asset liquid fund ',
 'aditya birla sun life midcap fund',
 'hsbc small cap fund',
 'mirae asset nifty midcap 150 etf',

---
Check ISIN Master

In [1]:
import pandas as pd
prt_data = pd.read_csv(r"Portfolio_extracted_091125-1636.csv")
isin_master = pd.read_excel(r"ISIN_master (2).xlsx",sheet_name="Combined ISIN List_Sel_Funds")

In [2]:
prt_data

,Name of Instrument,ISIN,Coupon,Industry,Quantity,Market Value,% to Net Assets,Yield,Type,Scheme Name,AMC,Scheme Name_df,isin_group,amfi_code
0,HDFC Bank Limited HDFB03,INE040A01034,0,Banks,1.016683e+08,966865.73,8.08,0,Equity & Equity Related,Parag Parikh Flexi Cap Fund (An open-ended dyn...,PPFAS Mutual Fund,parag parikh flexi cap fund,"INF879O01027,INF879O01019,INF879O01308,INF879O...","122639,122640,153964,153965"
1,Power Grid Corporation of India Limited PGCI01,INE752E01010,0,Power,2.559227e+08,717223.44,5.99,0,Equity & Equity Related,Parag Parikh Flexi Cap Fund (An open-ended dyn...,PPFAS Mutual Fund,parag parikh flexi cap fund,"INF879O01027,INF879O01019,INF879O01308,INF879O...","122639,122640,153964,153965"
2,Bajaj Holdings & Investment Limited BAJA01,INE118A01012,0,Finance,5.318918e+06,651407.89,5.44,0,Equity & Equity Related,Parag Parikh Flexi Cap Fund (An open-ended dyn...,PPFAS Mutual Fund,parag parikh flexi cap fund,"INF879O01027,INF879O01019,INF879O01308,INF879O...","122639,122640,153964,153965"
3,Coal India Limited COAL01,INE522F01014,0,Consumable Fuels,1.620396e+08,631873.26,5.28,0,Equity & Equity Related,Parag Parikh Flexi Cap Fund (An open-ended dyn...,PPFAS Mutual Fund,parag parikh flexi cap fund,"INF879O01027,INF879O01019,INF879O01308,INF879O...","122639,122640,153964,153965"
4,ICICI Bank Limited IBCL05,INE090A01021,0,Banks,4.221557e+07,569065.92,4.75,0,Equity & Equity Related,Parag Parikh Flexi Cap Fund (An open-ended dyn...,PPFAS Mutual Fund,parag parikh flexi cap fund,"INF879O01027,INF879O01019,INF879O01308,INF879O...","122639,122640,153964,153965"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,8.37% REC Ltd NCD Ser 169 (MD 07/12/2028) RECL355,INE020B08BH6,0,CRISIL AAA,5.000000e+01,524.56,0.20,0,Equity & Equity Related,Parag Parikh Dynamic Asset Allocation Fund (A...,PPFAS Mutual Fund,parag parikh dynamic asset allocation fund,"INF879O01233,INF879O01258,INF879O01266,INF879O...","152464,152467,152468,152469"
472,7.95% REC Ltd NCD (MD 12/03/2027) RECL318,INE020B08AH8,0,CRISIL AAA,5.000000e+01,508.95,0.20,0,Equity & Equity Related,Parag Parikh Dynamic Asset Allocation Fund (A...,PPFAS Mutual Fund,parag parikh dynamic asset allocation fund,"INF879O01233,INF879O01258,INF879O01266,INF879O...","152464,152467,152468,152469"
473,7.87% IndiGRID Infra Trust Ser Y (MD 24/02/202...,INE219X07454,0,CRISIL AAA,5.000000e+02,506.90,0.19,0,Equity & Equity Related,Parag Parikh Dynamic Asset Allocation Fund (A...,PPFAS Mutual Fund,parag parikh dynamic asset allocation fund,"INF879O01233,INF879O01258,INF879O01266,INF879O...","152464,152467,152468,152469"
474,6.07% NABARD NCD Sr MIF 1B (MD 19/11/2027) NBA...,INE261F08CM5,0,ICRA AAA,5.000000e+01,493.43,0.19,0,Equity & Equity Related,Parag Parikh Dynamic Asset Allocation Fund (A...,PPFAS Mutual Fund,parag parikh dynamic asset allocation fund,"INF879O01233,INF879O01258,INF879O01266,INF879O...","152464,152467,152468,152469"
475,Parag Parikh Liquid Fund- Direct Plan- Growth ...,INF879O01068,0,,7.952129e+05,11769.20,4.52,0,Equity & Equity Related,Parag Parikh Dynamic Asset Allocation Fund (A...,PPFAS Mutual Fund,parag parikh dynamic asset allocation fund,"INF879O01233,INF879O01258,INF879O01266,INF879O...","152464,152467,152468,152469"

In [3]:
available_isins = ",".join(prt_data["isin_group"].astype(str).unique())
available_isins

'INF879O01027,INF879O01019,INF879O01308,INF879O01324,INF879O01035,INF879O01043,INF879O01050,INF879O01076,INF879O01084,INF879O01118,INF879O01126,INF879O01134,INF879O01142,INF879O01068,INF879O01100,INF879O01092,INF879O01175,INF879O01209,INF879O01191,INF879O01183,INF879O01167,INF879O01159,INF879O01225,INF879O01217,INF879O01233,INF879O01258,INF879O01266,INF879O01282'

In [4]:
availability_stats = (
        isin_master.groupby("AMC").agg(
        master_isin_available_in_portfolio=("ISIN", lambda s: sum(s.apply(lambda x: str(x) in available_isins))),
        total_isins_in_master=("ISIN", lambda s: s.nunique())
    ).reset_index()
)
availability_stats

,AMC,master_isin_available_in_portfolio,total_isins_in_master
0,360_ONE_MUTUALFUND_MF,0,18
1,AXISMUTUALFUND_MF,0,84
2,BANDHANMUTUALFUND_MF,0,62
3,BANKOFINDIAMUTUALFUND_MF,0,23
4,BARODABNPPARIBASMUTUALFUND_MF,0,43
5,BirlaSunLifeMutualFund_MF,0,136
6,CANARAROBECOMUTUALFUND_MF,0,24
7,DSP_MF,0,92
8,EDELWEISSMUTUALFUND_MF,0,47
9,FRANKLINTEMPLETON,0,63
10,GROWWMUTUALFUND_MF,0,46
11,HDFCMutualFund_MF,0,121
12,HSBCMUTUALFUND_MF,0,69
13,ICICIPrudentialMutualFund_MF,0,199
14,ITI MUTUAL FUND_MF,0,17
15,JM FINANCIAL MUTUAL FUND_MF,0,30
16,KOTAKMAHINDRAMF,0,65
17,LICMUTUALFUND_MF,0,39
18,MAHINDRA MANULIFE MUTUAL FUND_MF,0,23
19,MIRAEASSET,0,38
20,MOTILALOSWAL_MF,0,32
21,NAVIMUTUALFUND_MF,0,17
22,NJMUTUALFUND_MF,0,5
23,NipponIndiaMutualFund_MF,0,67
24,OLDBRIDGEMUTUALFUND_MF,0,1
25,PGIMINDIAMUTUALFUND_MF,0,58
26,PPFAS_MF,6,6
27,QUANTMUTUALFUND_MF,0,28
28,QUANTUMMUTUALFUND_MF,0,12
29,SAMCOMUTUALFUND_MF,0,16
30,SBIMutualFund_MF,0,67
31,SHRIRAMMUTUALFUND_MF,0,6
32,SUNDARAMMUTUALFUND_MF,0,40
33,TATAMutualFund_MF,0,116
34,TAURUSMUTUALFUND_MF,0,15
35,TRUSTMUTUALFUND_MF,0,20
36,UNIONMUTUALFUND_MF,0,32
37,UTIMUTUALFUND_MF,0,93
38,WHITEOAKCAPITALMUTUALFUND_MF,0,21

In [ ]:
subset = ["icici" , "kotak" , "sbi" , "axis" , "ppfas", "dsp", "hdfc" , "nippon"]
print("\t".join(availability_stats.columns))
for idx, row in availability_stats.iterrows():
    row = row.astype(str).tolist()
    if(any(filter(lambda x : x in row[0].lower(), subset))):
        print("\t".join(row))

AMC	master_isin_available_in_portfolio	total_isins_in_master
PPFAS_MF	6	6